export enum StatusNota {
  RASCUNHO = 'RASCUNHO',
  ASSINADA = 'ASSINADA',
  ENVIADA = 'ENVIADA',
  AUTORIZADA = 'AUTORIZADA',
  REJEITADA = 'REJEITADA',
  CANCELADA = 'CANCELADA',
  ERRO = 'ERRO',
}
